create column table "NYPFYPJ03"."USER_PROFILE"( 
	 "USER_ID" VARCHAR (11) not null,
	 "DOB" DATE not null,
	 "AGE" INTEGER not null,
	 "RACE" VARCHAR (20) null,
	 "ASTHMATIC_LEVEL" INTEGER not null,
	 "CONTACT_NO" VARCHAR (15) null,
	 "EMAIL" VARCHAR (100) null,
	 "ROLE" VARCHAR (10) not null,
	 "REGISTERED_ON" TIMESTAMP null,
	 primary key ("USER_ID")) 
;
comment on column "NYPFYPJ03"."USER_PROFILE"."USER_ID" is 'SAP account Id' 
;
comment on column "NYPFYPJ03"."USER_PROFILE"."AGE" is 'Derived from DOB' 
;
comment on column "NYPFYPJ03"."USER_PROFILE"."ASTHMATIC_LEVEL" is 'level 0 - Nil;
level 1 - Intermittent Asthma;
level 2 - Mild Persistent Asthma;
level 3 - Moderate Persistent Asthma;
level 4 - Severe Persistent Asthma;' 
;
comment on column "NYPFYPJ03"."USER_PROFILE"."ROLE" is 'user/admin'
;
create column table "NYPFYPJ03"."IOT_DEVICE"( 
	 "DEVICE_SN" VARCHAR (11) not null,
	 "MANUFACTURED_ON" TIMESTAMP null,
	 "SYSTEM_PLATFORM" VARCHAR (10) null,
	 "APPLICATION_VERSION" VARCHAR (10) null,
	 "SENSOR_HUMIDITY" VARCHAR (1) null,
	 "SENSOR_TEMPERATURE" VARCHAR (1) null,
	 "SENSOR_BUTTON" VARCHAR (1) null,
	 "SENSOR_AIR_QUALITY" VARCHAR (1) null,
	 "ACTUATOR_BUZZER" VARCHAR (1) null,
	 "ACTUATOR_LED" VARCHAR (1) null,
	 "ACTUATOR_DISPLAY" VARCHAR (1) null,
	 primary key ("DEVICE_SN")) 
;
comment on column "NYPFYPJ03"."IOT_DEVICE"."SENSOR_HUMIDITY" is 'Y/N' 
;
comment on column "NYPFYPJ03"."IOT_DEVICE"."SENSOR_TEMPERATURE" is 'Y/N' 
;
comment on column "NYPFYPJ03"."IOT_DEVICE"."SENSOR_BUTTON" is 'Y/N' 
;
comment on column "NYPFYPJ03"."IOT_DEVICE"."SENSOR_AIR_QUALITY" is 'Y/N' 
;
comment on column "NYPFYPJ03"."IOT_DEVICE"."ACTUATOR_BUZZER" is 'Y/N' 
;
comment on column "NYPFYPJ03"."IOT_DEVICE"."ACTUATOR_LED" is 'Y/N' 
;
comment on column "NYPFYPJ03"."IOT_DEVICE"."ACTUATOR_DISPLAY" is 'Y/N'
;
create column table "NYPFYPJ03"."USER_DEVICES"( 
	 "USER_ID" VARCHAR (11) not null,
	 "DEVICE_SN" VARCHAR (11) not null,
	 "DEVICE_NAME" VARCHAR (100) null default 'My Smart Backpack',
	 "REGISTERED_ON" TIMESTAMP null,
	 "CONFIG_ENABLE_BUZZER" VARCHAR (1) null,
	 "CONFIG_ENABLE_LED" VARCHAR (1) null,
	 "MINUTES_TO_RECORD_DATA" INTEGER null,
	 "LAST_ONLINE" TIMESTAMP null,
	 primary key ("USER_ID","DEVICE_SN")) 
;
comment on column "NYPFYPJ03"."USER_DEVICES"."CONFIG_ENABLE_BUZZER" is 'Y/N' 
;
comment on column "NYPFYPJ03"."USER_DEVICES"."CONFIG_ENABLE_LED" is 'Y/N'
;
create column table "NYPFYPJ03"."IOT_DATA"( 
	 "DATA_ID" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	 "DEVICE_SN" VARCHAR (11) null,
	 "USER_ID" VARCHAR (11) not null,
	 "RECORDED_ON" TIMESTAMP not null,
	 "GEO_LOCATION" VARCHAR (100) null,
	 "HUMIDITY" DOUBLE null,
	 "TEMPERATURE" DOUBLE null,
	 "PM2_5" DOUBLE null,
	 "PM10" DOUBLE null,
	 "PREDICTED_COMFORT_LEVEL" INTEGER null,
	 "USER_FEEDBACK_COMFORT_LEVEL" INTEGER null,
	 "ALERT_TRIGGERED" VARCHAR (1) null,
	 primary key ("DATA_ID")) 
;
comment on column "NYPFYPJ03"."IOT_DATA"."GEO_LOCATION" is '[lat,lng]'
;
comment on column "NYPFYPJ03"."IOT_DATA"."ALERT_TRIGGERED" is 'Y/N'
;