CREATE COLUMN TABLE "NYPFYPJ03"."USER_PROFILE" ("USER_ID" VARCHAR(11) NOT NULL , "DOB" DATE CS_DAYDATE NOT NULL , "RACE" VARCHAR(20), "ASTHMATIC_LEVEL" INTEGER CS_INT NOT NULL , "CONTACT_NO" VARCHAR(15), "EMAIL" VARCHAR(100), "ROLE" VARCHAR(10) NOT NULL , "REGISTERED_ON" LONGDATE CS_LONGDATE, "NAME" VARCHAR(100) NOT NULL , "GENDER" VARCHAR(1) NOT NULL , "CITY" VARCHAR(100), "STATE" VARCHAR(100), "COUNTRY" VARCHAR(100), "COUNTRY_CODE" VARCHAR(2), PRIMARY KEY ("USER_ID")) UNLOAD PRIORITY 5  AUTO MERGE ;
COMMENT ON COLUMN "NYPFYPJ03"."USER_PROFILE"."USER_ID" is 'SAP account Id';
COMMENT ON COLUMN "NYPFYPJ03"."USER_PROFILE"."ASTHMATIC_LEVEL" is 'level 0 - Nil;
level 1 - Intermittent Asthma;
level 2 - Mild Persistent Asthma;
level 3 - Moderate Persistent Asthma;
level 4 - Severe Persistent Asthma;';
COMMENT ON COLUMN "NYPFYPJ03"."USER_PROFILE"."ROLE" is 'user/admin'