CREATE COLUMN TABLE "NYPFYPJ03"."IOT_DEVICE" ("DEVICE_SN" VARCHAR(11) NOT NULL , "MANUFACTURED_ON" LONGDATE CS_LONGDATE, "SYSTEM_PLATFORM" VARCHAR(10), "APPLICATION_VERSION" VARCHAR(10), "SENSOR_HUMIDITY" VARCHAR(1), "SENSOR_TEMPERATURE" VARCHAR(1), "SENSOR_BUTTON" VARCHAR(1), "SENSOR_AIR_QUALITY" VARCHAR(1), "ACTUATOR_BUZZER" VARCHAR(1), "ACTUATOR_LED" VARCHAR(1), "ACTUATOR_DISPLAY" VARCHAR(1), "ACTIVATED_ON" LONGDATE CS_LONGDATE, "DEVICE_ADDRESS" VARCHAR(50), PRIMARY KEY ("DEVICE_SN")) UNLOAD PRIORITY 5  AUTO MERGE ;
COMMENT ON COLUMN "NYPFYPJ03"."IOT_DEVICE"."SENSOR_HUMIDITY" is 'Y/N';
COMMENT ON COLUMN "NYPFYPJ03"."IOT_DEVICE"."SENSOR_TEMPERATURE" is 'Y/N';
COMMENT ON COLUMN "NYPFYPJ03"."IOT_DEVICE"."SENSOR_BUTTON" is 'Y/N';
COMMENT ON COLUMN "NYPFYPJ03"."IOT_DEVICE"."SENSOR_AIR_QUALITY" is 'Y/N';
COMMENT ON COLUMN "NYPFYPJ03"."IOT_DEVICE"."ACTUATOR_BUZZER" is 'Y/N';
COMMENT ON COLUMN "NYPFYPJ03"."IOT_DEVICE"."ACTUATOR_LED" is 'Y/N';
COMMENT ON COLUMN "NYPFYPJ03"."IOT_DEVICE"."ACTUATOR_DISPLAY" is 'Y/N'