CREATE ROW TABLE "NYPFYPJ03"."ACCOUNT_DEVICE" ( 
	"ACCOUNT_ID" bigint NOT NULL,
	 "DEVICE_ID" bigint NOT NULL,
	 "REGISTERED_ON" LONGDATE CS_LONGDATE,
	 "CONNECTED_THROUGH" VARCHAR(50) CS_STRING,
	 "CONNECTED_IP" VARCHAR(32) CS_STRING,
	 "MINUTE_TO_RECORD_DATA" DOUBLE CS_DOUBLE DEFAULT 0.2,
	 "SECONDS_TO_UPDATE_DATA" INT CS_INT DEFAULT 5,
	 "ENABLE_LED" VARCHAR CS_STRING DEFAULT 'Y',
	 "ENABLE_BUZZER" VARCHAR CS_STRING DEFAULT 'Y',
	 primary key("ACCOUNT_ID","DEVICE_ID") ) 