create COLUMN table "NYPFYPJ03"."ACCOUNT"( 
	 "ACCOUNT_ID" bigint NOT NULL primary key GENERATED BY DEFAULT AS IDENTITY,
	 "EMAIL" VARCHAR (50) not null,
	 "PASSWORD" VARCHAR (32) not null,
	 "REGISTERED_ON" TIMESTAMP null,
	 "LAST_ONLINE" TIMESTAMP null,
	 "IS_VALID" VARCHAR (1) not null default 'T') 
;
comment on column "NYPFYPJ03"."ACCOUNT"."PASSWORD" is 'Encrypted password'